[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
pluginx = { path = "../../", features = ["server"] }
shared = { path = "../shared" }
tokio = { version = "1", features = ["full"] }
