pub const PLUGIN_MIN_PORT: &str = "PLUGIN_MIN_PORT";
pub const PLUGIN_MAX_PORT: &str = "PLUGIN_MAX_PORT";
pub const PLUGIN_PROTOCOL_VERSIONS: &str = "PLUGIN_PROTOCOL_VERSIONS";
pub const PLUGIN_UNIX_SOCKET_DIR: &str = "PLUGIN_UNIX_SOCKET_DIR";
pub const PLUGIN_UNIX_SOCKET_GROUP: &str = "PLUGIN_UNIX_SOCKET_GROUP";
pub const PLUGIN_MULTIPLEX_GRPC: &str = "PLUGIN_MULTIPLEX_GRPC";
pub const PLUGIN_CLIENT_CERT: &str = "PLUGIN_CLIENT_CERT";
